# Generated by Django 4.2.17 on 2025-01-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0002_customuser_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(max_length=100),
        ),
    ]
