# Generated by Django 4.2.17 on 2025-01-17 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0004_user_delete_customuser"),
    ]

    operations = [
        migrations.DeleteModel(name="User",),
    ]
