# Generated by Django 4.2.17 on 2025-01-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0008_devicemetadata_delete_devicedata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicemetadata",
            name="register_name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
