# Generated by Django 4.2.17 on 2025-01-22 11:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0009_alter_devicemetadata_register_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100)),
                ("value", models.FloatField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        to="userapp.device",
                    ),
                ),
            ],
            options={"ordering": ["-timestamp"],},
        ),
    ]
