# Generated by Django 4.2.17 on 2025-01-22 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0010_devicedata"),
    ]

    operations = [
        migrations.DeleteModel(name="DeviceMetadata",),
    ]
