# Generated by Django 4.2.17 on 2025-02-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0012_device_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device", name="status", field=models.BooleanField(default=True),
        ),
    ]
