# Generated by Django 4.2.17 on 2025-02-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0013_alter_device_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")], max_length=50
            ),
        ),
    ]
